version: '3'

services:
  eureka-server:
    build: ../eureka-server
    ports:
      - "8761:8761"

  config-server:
    build: ../config-server
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server

  api-gateway:
    build: ../api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - config-server

  auth-service:
    build: ../auth-service
    depends_on:
      - eureka-server
      - config-server
      - keycloak

  product-service:
    build: ../product-service
    depends_on:
      - eureka-server
      - config-server
      - mongodb

  order-service:
    build: ../order-service
    depends_on:
      - eureka-server
      - config-server
      - postgres
      - kafka

  inventory-service:
    build: ../inventory-service
    depends_on:
      - eureka-server
      - config-server
      - postgres
      - kafka

  payment-service:
    build: ../payment-service
    depends_on:
      - eureka-server
      - config-server
      - postgres
      - kafka

  notification-service:
    build: ../notification-service
    depends_on:
      - eureka-server
      - config-server
      - kafka

  analytics-service:
    build: ../analytics-service
    depends_on:
      - eureka-server
      - config-server
      - kafka

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  keycloak:
    image: jboss/keycloak:15.0.2
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  grafana:
    image: grafana/grafana:8.0.0
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - victoria-metrics

  victoria-metrics:
    image: victoriametrics/victoria-metrics:v1.64.0
    ports:
      - "8428:8428"
    volumes:
      - victoria-metrics-data:/victoria-metrics-data
    command:
      - '--storageDataPath=/victoria-metrics-data'
      - '--httpListenAddr=:8428'

volumes:
  postgres-data:
  mongo-data:
  grafana-storage:
  victoria-metrics-data: