server:
  port: 8082

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/ecommerce
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: product-service-group

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true