apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ecommerce-services
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: ecommerce
  endpoints:
    - port: web
